"""
author: mengjianhua
date: 2019/5/8
"""

HEALTH_LEVEL = 10

BATTERY_HEALTH = {
    1: 'BATTERY_HEALTH_UNKNOWN',
    2: 'BATTERY_HEALTH_GOOD',
    3: 'BATTERY_HEALTH_OVERHEAT',
    4: 'BATTERY_HEALTH_DEAD',
    5: 'BATTERY_HEALTH_OVER_VOLTAGE',
    6: 'BATTERY_HEALTH_UNSPECIFIED_FAILURE',
    7: 'BATTERY_HEALTH_COLD',
}
